# GitLab CI configuration for MCP Server
stages:
  - test
  - security
  - deploy

# Cache node_modules for faster builds
.node_cache: &node_cache
  cache:
    key: 
      files:
        - package-lock.json
    paths:
      - node_modules/
    policy: pull-push

# Template for Node.js jobs
.node_job: &node_job
  image: node:${NODE_VERSION}
  <<: *node_cache
  before_script:
    - npm ci

# Test job that runs on multiple Node.js versions
test:
  <<: *node_job
  stage: test
  tags:
    - docker_runner-build
  parallel:
    matrix:
      - NODE_VERSION: ["17", "18", "20", "22"]
  script:
    - npm run lint --if-present
    - npm run build
    - npm run test:ci
  coverage: '/All files[^|]*\|[^|]*\s+([\d\.]+)/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage/cobertura-coverage.xml
    paths:
      - coverage/
    expire_in: 1 week
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+$/

# Security audit job
security_audit:
  image: node:20
  <<: *node_cache
  stage: security
  tags:
    - docker_runner-build
  script:
    - npm audit --audit-level=moderate
  allow_failure: false
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+$/

# Sync to GitHub and create release (triggers NPM publishing)
sync_to_github:
  stage: deploy
  image: node:20
  tags:
    - docker_runner-build
  variables:
    GIT_STRATEGY: clone
    GIT_DEPTH: 0
  before_script:
    - npm ci
    - git config --global user.email "ci@name.systems"
    - git config --global user.name "GitLab CI"
    - git remote add github https://${GITHUB_USERNAME}:${GITHUB_TOKEN}@github.com/namedotcom/namecom-mcp
    # Install GitHub CLI for release creation
    - apt-get update && apt-get install -y curl
    - curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
    - echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | tee /etc/apt/sources.list.d/github-cli.list > /dev/null
    - apt-get update && apt-get install -y gh
  script:
    # Build and test
    - npm run build
    - npm run test:ci
    
    # Sync to GitHub
    - echo "Syncing tag ${CI_COMMIT_TAG} to GitHub..."
    - git push github HEAD:main --force
    - git push github ${CI_COMMIT_TAG}
    - echo "✅ Successfully synced to GitHub!"
    
    # Create GitHub release (this triggers NPM publishing via GitHub Actions)
    - echo "Creating GitHub release for ${CI_COMMIT_TAG}..."
    - export GITHUB_TOKEN=${GITHUB_TOKEN}
    - gh release create ${CI_COMMIT_TAG} --repo namedotcom/namecom-mcp --title "Release ${CI_COMMIT_TAG}" --notes "Automatically created from GitLab tag ${CI_COMMIT_TAG}" --generate-notes
    - echo "🚀 GitHub release created! NPM publishing will be triggered automatically."
  rules:
    - if: $CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+$/
  needs:
    - test
    - security_audit 